-- DDL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE RedeSocial

USE RedeSocial

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
)

CREATE TABLE Postagem(
	Id INT PRIMARY KEY NOT NULL,
	Descricao VARCHAR(50)
)

CREATE TABLE Temas(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	NomePostagem VARCHAR(50) NOT NULL,
	Descricao VARCHAR(150) NOT NULL,
	FK_Criador INT NOT NULL,
	FK_Postagem INT NOT NULL,
	FOREIGN KEY (FK_Criador) REFERENCES Usuarios (Id),
	FOREIGN KEY (FK_Postagem) REFERENCES Postagem (Id)
)
